site_name: Nick's Docs
repo_url: https://github.com/tpbnick/docs
repo_name: tpbnick/docs
edit_uri: ""

theme:
 name: material
 logo: "https://cdn.nickplatt.dev/Misc/logo-dracula.png"
 favicon: "https://cdn.nickplatt.dev/Misc/logo-dracula.png"
 features:
  - navigation.instant
  - navigation.tabs
  - navigation.top
  - navigation.tracking
  - search.suggest
  - search.highlight
 static_templates:
  - 404.html
 palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
     icon: material/lightbulb
     name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
     icon: material/lightbulb-outline
     name: Switch to light mode
 font:
  text: Roboto
  code: Roboto Mono
 icon:
  repo: fontawesome/brands/git-alt

extra_css:
 - stylesheets/extra.css

plugins:
 - search
 # glightbox disabled: was breaking all images; use manual mode to enable per-image
 # - glightbox
 - awesome-pages
 - minify:
    minify_html: true

extra_javascript:
 # NOTE: MathJax v2 is legacy but kept to preserve your current behavior.
 - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
 - pymdownx.arithmatex
 - attr_list

 # Modern replacement for deprecated `codehilite`
 - pymdownx.highlight:
    guess_lang: false
    pygments_lang_class: true
    linenums: true
 - pymdownx.inlinehilite
 - pymdownx.superfences

 - admonition
 - pymdownx.details

 # Updated module path for Material emoji integration
 - pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg

 - pymdownx.magiclink
 - pymdownx.mark
 - pymdownx.smartsymbols
 - pymdownx.tasklist:
    custom_checkbox: true

 # Modern recommended config for tabs
 - pymdownx.tabbed:
    alternate_style: true

 - pymdownx.tilde
 - toc:
    permalink: false

extra:
 social:
  - icon: fontawesome/solid/images
    link: https://nickplatt.dev
  - icon: fontawesome/solid/blog
    link: https://blog.nickplatt.dev
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/nicholas-platt/
  - icon: fontawesome/brands/github
    link: https://github.com/tpbnick
  - icon: fontawesome/brands/instagram
    link: https://www.instagram.com/nickplattfour/
  - icon: fontawesome/regular/envelope
    link: mailto:nick@nickplatt.dev
 generator: false
